version: 2
jobs:
  build:
    docker:
      - image: namachan10777/misc3d:latest

    steps:
      - checkout

      - run:
          name: init submodules
          command: git submodule update --init --recursive
      - run:
          name: build namecard-box
          command: eval $(opam env) && make -C namecard-box
      - store_artifacts:
          path: ./namecard-box/namecard-box.stl
          destination: namecard-box.stl
